name: Cloudflare Debug Verify

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Check secrets present
        run: |
          if [ -z "${{ secrets.CF_API_TOKEN }}" ]; then echo "CF_API_TOKEN is EMPTY"; exit 1; else echo "CF_API_TOKEN is set"; fi

      - name: Verify token
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: |
          curl -i -s -X GET \
            -H "Authorization: Bearer ${CF_API_TOKEN}" \
            https://api.cloudflare.com/client/v4/user/tokens/verify | sed -e 's/^/VERIFY: /'

      - name: List accounts
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: |
          curl -i -s \
            -H "Authorization: Bearer ${CF_API_TOKEN}" \
            https://api.cloudflare.com/client/v4/accounts | sed -e 's/^/ACCOUNTS: /'

      - name: List projects (if CF_ACCOUNT_ID set)
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        run: |
          if [ -z "${CF_ACCOUNT_ID}" ]; then
            echo "No CF_ACCOUNT_ID secret set yet, skipping"
            exit 0
          fi
          curl -i -s \
            -H "Authorization: Bearer ${CF_API_TOKEN}" \
            "https://api.cloudflare.com/client/v4/accounts/${CF_ACCOUNT_ID}/pages/projects" | sed -e 's/^/PROJECTS: /'
