name: Comment Cloudflare Pages Preview URL

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Check required secrets
        run: |
          test -n "${{ secrets.CF_API_TOKEN }}" || (echo "Missing CF_API_TOKEN" && exit 1)
          test -n "${{ secrets.CF_ACCOUNT_ID }}" || (echo "Missing CF_ACCOUNT_ID" && exit 1)
          test -n "${{ secrets.CF_PAGES_PROJECT }}" || (echo "Missing CF_PAGES_PROJECT" && exit 1)

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Poll Cloudflare for preview URL (up to 6 min)
        id: cf
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_PAGES_PROJECT: ${{ secrets.CF_PAGES_PROJECT }}
          BRANCH: ${{ github.event.pull_request.head.ref }}
        run: |
          set -euo pipefail
          API="https://api.cloudflare.com/client/v4/accounts/${CF_ACCOUNT_ID}/pages/projects/${CF_PAGES_PROJECT}/deployments?page=1&per_page=50"
          PREVIEW_URL=""
          for i in $(seq 1 24); do
            RESP="$(curl -fsSL -H "Authorization: Bearer ${CF_API_TOKEN}" "$API" || true)"
            PREVIEW_URL="$(echo "$RESP" | jq -r --arg BRANCH "$BRANCH" '
              .result
              | map(select(.environment=="preview" and (.deployment_trigger.metadata.branch==$BRANCH)))
              | sort_by(.created_on) | reverse | (.[0].url // empty)
            ')"
            if [ -n "$PREVIEW_URL" ]; then
              echo "Found preview: $PREVIEW_URL"
              break
            fi
            echo "Preview not ready yet (branch=$BRANCH). Waiting 15s..."
            sleep 15
          done
          echo "preview_url=$PREVIEW_URL" >> "$GITHUB_OUTPUT"

      - name: Post/Update sticky PR comment
        if: steps.cf.outputs.preview_url != ''
        uses: actions/github-script@v7
        env:
          PREVIEW_URL: ${{ steps.cf.outputs.preview_url }}
        with:
          script: |
            const marker = "<!-- PREEV_PREVIEW_LINK -->";
            const { owner, repo, number } = context.issue;
            const urlWithParams = `${process.env.PREVIEW_URL}?repo=${owner}%2F${repo}&pr=${number}`;
            const body = `${marker}
            🚀 Preview is ready:

            ${urlWithParams}

            (Cloudflare Pages)`;
            const { data: comments } = await github.rest.issues.listComments({ owner, repo, issue_number: number });
            const existing = comments.find(c => c.user?.type === "Bot" && c.body?.includes(marker));
            if (existing) {
              await github.rest.issues.updateComment({ owner, repo, comment_id: existing.id, body });
            } else {
              await github.rest.issues.createComment({ owner, repo, issue_number: number, body });
            }

      - name: No preview yet (give hint)
        if: steps.cf.outputs.preview_url == ''
        run: echo "No preview found. Wait for Pages to finish building, then push a new commit to retrigger."
