name: Cloudflare Debug Accounts & Projects

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Verify token
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: |
          curl -fsSL -H "Authorization: Bearer ${CF_API_TOKEN}" \
            https://api.cloudflare.com/client/v4/user/tokens/verify | jq .

      - name: List accounts
        id: accounts
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: |
          ACCOUNTS_JSON=$(curl -fsSL -H "Authorization: Bearer ${CF_API_TOKEN}" \
            https://api.cloudflare.com/client/v4/accounts)
          echo "Accounts (ID  NAME):"
          echo "$ACCOUNTS_JSON" | jq -r '.result[] | "\(.id)  \(.name)"'
          echo "ids=$(echo "$ACCOUNTS_JSON" | jq -r '[.result[].id] | join(",")')" >> $GITHUB_OUTPUT

      - name: List Pages projects for each account
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          IDS: ${{ steps.accounts.outputs.ids }}
        run: |
          IFS=',' read -ra ARR <<< "$IDS"
          for ID in "${ARR[@]}"; do
            echo "---- Account $ID projects ----"
            curl -fsSL -H "Authorization: Bearer ${CF_API_TOKEN}" \
              "https://api.cloudflare.com/client/v4/accounts/${ID}/pages/projects" \
              | jq -r '.result[]?.name'
          done
